/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parlor_services;

import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Queue;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author hanne
 */
public class Services_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Services_Frame
     */
    
    double total=0, payment=0, change=0;
    ArrayList<String> selectedServices = new ArrayList<>();
    String name="", sex="", contact="", orderList = "";
    Queue<String> queueName = new LinkedList<>();
    
    
    
    public Services_Frame() {
        initComponents();
         plQueue.setLayout(new javax.swing.BoxLayout(plQueue, javax.swing.BoxLayout.Y_AXIS));
         receiptPanel.setLayout(new javax.swing.BoxLayout(receiptPanel, javax.swing.BoxLayout.Y_AXIS));
    }
    
    public class ServiceSelector {

    private Queue<String> servicesID = new LinkedList<>();

    // Constructor
    public ServiceSelector() {
        // Set IDs for Hair Care services (4 services)
        for (int i = 1; i <= 4; i++) {
            servicesID.add("HC" + i);
        }

        // Set IDs for Body Massage services (4 services)
        for (int i = 1; i <= 4; i++) {
            servicesID.add("BM" + i);
        }

        // Set IDs for Waxing services (4 services)
        for (int i = 1; i <= 4; i++) {
            servicesID.add("WX" + i);
        }

        // Set IDs for Nail Care services (3 services)
        for (int i = 1; i <= 3; i++) {
            servicesID.add("NC" + i);
        }
    }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        receiptWindow = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        receiptPanel = new javax.swing.JPanel();
        btConfirm2 = new javax.swing.JButton();
        btConfirm3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cbHairCare1 = new javax.swing.JCheckBox();
        cbHairCare2 = new javax.swing.JCheckBox();
        cbHairCare3 = new javax.swing.JCheckBox();
        cbHairCare4 = new javax.swing.JCheckBox();
        cbBodyMassage4 = new javax.swing.JCheckBox();
        cbBodyMassage3 = new javax.swing.JCheckBox();
        cbBodyMassage2 = new javax.swing.JCheckBox();
        cbBodyMassage1 = new javax.swing.JCheckBox();
        cbWaxing1 = new javax.swing.JCheckBox();
        cbWaxing2 = new javax.swing.JCheckBox();
        cbWaxing3 = new javax.swing.JCheckBox();
        cbWaxing4 = new javax.swing.JCheckBox();
        cbNailCare1 = new javax.swing.JCheckBox();
        cbNailCare2 = new javax.swing.JCheckBox();
        cbNailCare3 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btDelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbhaircare = new javax.swing.JLabel();
        lbbodymassage = new javax.swing.JLabel();
        lbWaxing = new javax.swing.JLabel();
        lbNailCare = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbquestion1 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        lbquestion2 = new javax.swing.JLabel();
        tfcontactnumber = new javax.swing.JTextField();
        lbquestion3 = new javax.swing.JLabel();
        jcSex = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        lbquestion4 = new javax.swing.JLabel();
        lbquestion5 = new javax.swing.JLabel();
        plQueue = new javax.swing.JPanel();
        btConfirm1 = new javax.swing.JButton();
        lbTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpAmount = new javax.swing.JTextPane();
        lbhaircare1 = new javax.swing.JLabel();
        lbhaircare2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbquestion6 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        receiptWindow.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        receiptWindow.setResizable(false);
        receiptWindow.setSize(new java.awt.Dimension(543, 649));

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel3.setText("Receipt");

        receiptPanel.setBackground(new java.awt.Color(255, 255, 255));
        receiptPanel.setPreferredSize(new java.awt.Dimension(489, 489));

        javax.swing.GroupLayout receiptPanelLayout = new javax.swing.GroupLayout(receiptPanel);
        receiptPanel.setLayout(receiptPanelLayout);
        receiptPanelLayout.setHorizontalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        receiptPanelLayout.setVerticalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        btConfirm2.setBackground(new java.awt.Color(255, 204, 102));
        btConfirm2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btConfirm2.setText("Add");
        btConfirm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirm2ActionPerformed(evt);
            }
        });

        btConfirm3.setBackground(new java.awt.Color(255, 204, 102));
        btConfirm3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btConfirm3.setText("Done");
        btConfirm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirm3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(receiptPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                            .addComponent(btConfirm3, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel3)))
                .addGap(64, 64, 64))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(203, 203, 203)
                    .addComponent(btConfirm2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(195, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(receiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConfirm3)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(304, 304, 304)
                    .addComponent(btConfirm2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(305, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout receiptWindowLayout = new javax.swing.GroupLayout(receiptWindow.getContentPane());
        receiptWindow.getContentPane().setLayout(receiptWindowLayout);
        receiptWindowLayout.setHorizontalGroup(
            receiptWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        receiptWindowLayout.setVerticalGroup(
            receiptWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptWindowLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        cbHairCare1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbHairCare1.setText("Wash and Cut - 100 php");
        cbHairCare1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHairCare1ActionPerformed(evt);
            }
        });

        cbHairCare2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbHairCare2.setText("Rebond - 1,500 php");
        cbHairCare2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHairCare2ActionPerformed(evt);
            }
        });

        cbHairCare3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbHairCare3.setText("Brazilian - 800 php");
        cbHairCare3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHairCare3ActionPerformed(evt);
            }
        });

        cbHairCare4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbHairCare4.setText("Hair Color - 500 php");
        cbHairCare4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHairCare4ActionPerformed(evt);
            }
        });

        cbBodyMassage4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbBodyMassage4.setText("Legs - 400 php");
        cbBodyMassage4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBodyMassage4ActionPerformed(evt);
            }
        });

        cbBodyMassage3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbBodyMassage3.setText("Shoulders - 250 php");
        cbBodyMassage3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBodyMassage3ActionPerformed(evt);
            }
        });

        cbBodyMassage2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbBodyMassage2.setText("Full Body - 250 php");
        cbBodyMassage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBodyMassage2ActionPerformed(evt);
            }
        });

        cbBodyMassage1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbBodyMassage1.setText("Head - 600 php");
        cbBodyMassage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBodyMassage1ActionPerformed(evt);
            }
        });

        cbWaxing1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbWaxing1.setText("Full Body - 600 php");
        cbWaxing1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbWaxing1ActionPerformed(evt);
            }
        });

        cbWaxing2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbWaxing2.setText("Face - 250 php");
        cbWaxing2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbWaxing2ActionPerformed(evt);
            }
        });

        cbWaxing3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbWaxing3.setText("Armpit - 250 php");
        cbWaxing3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbWaxing3ActionPerformed(evt);
            }
        });

        cbWaxing4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbWaxing4.setText("Legs - 400 php");
        cbWaxing4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbWaxing4ActionPerformed(evt);
            }
        });

        cbNailCare1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbNailCare1.setText("Full Nail Care - 250 php");
        cbNailCare1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNailCare1ActionPerformed(evt);
            }
        });

        cbNailCare2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbNailCare2.setText("Hands Only - 125 php");
        cbNailCare2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNailCare2ActionPerformed(evt);
            }
        });

        cbNailCare3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbNailCare3.setText("Foot Only - 125 php");
        cbNailCare3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNailCare3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel2.setText("Parlor Services and Payment");

        btDelete.setBackground(new java.awt.Color(255, 204, 102));
        btDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btDelete.setText("Complete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parlor_services/4-1.png"))); // NOI18N

        lbhaircare.setFont(new java.awt.Font("Segoe UI Variable", 1, 20)); // NOI18N
        lbhaircare.setText("Hair Care");

        lbbodymassage.setFont(new java.awt.Font("Segoe UI Variable", 1, 20)); // NOI18N
        lbbodymassage.setText("Body Massage");

        lbWaxing.setFont(new java.awt.Font("Segoe UI Variable", 1, 20)); // NOI18N
        lbWaxing.setText("Waxing");

        lbNailCare.setFont(new java.awt.Font("Segoe UI Variable", 1, 20)); // NOI18N
        lbNailCare.setText("Nail Care");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbquestion1.setFont(new java.awt.Font("Segoe UI Variable", 1, 20)); // NOI18N
        lbquestion1.setText("What services do you want?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addComponent(lbquestion1)
                .addGap(291, 291, 291))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbquestion1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tfname.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameActionPerformed(evt);
            }
        });

        lbquestion2.setFont(new java.awt.Font("Segoe UI Variable", 1, 20)); // NOI18N
        lbquestion2.setText("Contact number");

        tfcontactnumber.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        lbquestion3.setFont(new java.awt.Font("Segoe UI Variable", 1, 20)); // NOI18N
        lbquestion3.setText("Sex");

        jcSex.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jcSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jcSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcSexActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbquestion4.setFont(new java.awt.Font("Segoe UI Variable", 1, 20)); // NOI18N
        lbquestion4.setText("Customer's Information");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbquestion4)
                .addGap(305, 305, 305))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbquestion4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbquestion5.setFont(new java.awt.Font("Segoe UI Variable", 1, 20)); // NOI18N
        lbquestion5.setText("Name");

        plQueue.setBackground(new java.awt.Color(255, 255, 255));
        plQueue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        plQueue.setPreferredSize(new java.awt.Dimension(350, 500));

        javax.swing.GroupLayout plQueueLayout = new javax.swing.GroupLayout(plQueue);
        plQueue.setLayout(plQueueLayout);
        plQueueLayout.setHorizontalGroup(
            plQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        plQueueLayout.setVerticalGroup(
            plQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        btConfirm1.setBackground(new java.awt.Color(255, 204, 102));
        btConfirm1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btConfirm1.setText("Confirm");
        btConfirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirm1ActionPerformed(evt);
            }
        });

        lbTotal.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbTotal.setText("Php 0.0");

        tpAmount.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jScrollPane1.setViewportView(tpAmount);

        lbhaircare1.setFont(new java.awt.Font("Segoe UI Variable", 1, 20)); // NOI18N
        lbhaircare1.setText("Total :");

        lbhaircare2.setFont(new java.awt.Font("Segoe UI Variable", 1, 20)); // NOI18N
        lbhaircare2.setText("Amount :");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lbquestion6.setFont(new java.awt.Font("Segoe UI Variable", 1, 20)); // NOI18N
        lbquestion6.setText("Queueing Tab");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(lbquestion6)
                .addGap(115, 115, 115))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lbquestion6)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(42, 42, 42)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lbquestion2)
                                                .addComponent(lbquestion3)
                                                .addComponent(lbquestion5))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(tfname)
                                                    .addComponent(tfcontactnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jcSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbHairCare1)
                                            .addComponent(cbHairCare2)
                                            .addComponent(cbHairCare3)
                                            .addComponent(cbHairCare4)
                                            .addComponent(lbhaircare))
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbBodyMassage4)
                                            .addComponent(cbBodyMassage2)
                                            .addComponent(cbBodyMassage3)
                                            .addComponent(cbBodyMassage1)
                                            .addComponent(lbbodymassage))
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbWaxing2)
                                            .addComponent(cbWaxing1)
                                            .addComponent(cbWaxing3)
                                            .addComponent(cbWaxing4)
                                            .addComponent(lbWaxing))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbNailCare)
                                            .addComponent(cbNailCare1)
                                            .addComponent(cbNailCare2)
                                            .addComponent(cbNailCare3))))
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbhaircare1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbhaircare2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                                .addComponent(btConfirm1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(189, 189, 189)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(plQueue, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(70, 70, 70)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbquestion5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbquestion2)
                            .addComponent(tfcontactnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbquestion3)
                            .addComponent(jcSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbhaircare)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbHairCare1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbHairCare2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbHairCare3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbHairCare4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbbodymassage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbBodyMassage1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbBodyMassage2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbBodyMassage3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbBodyMassage4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbNailCare)
                                    .addComponent(lbWaxing))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbNailCare1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbNailCare2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbNailCare3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbWaxing1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbWaxing2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbWaxing3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbWaxing4)))))
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(plQueue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btConfirm1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbhaircare1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbhaircare2))))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbHairCare1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHairCare1ActionPerformed

        if(cbHairCare1.isSelected()) {
            addService(100);
            lbTotal.setText("Php "+total);
            selectedServices.add(cbHairCare1.getText());
            
        } else {
            removeService(100);
            lbTotal.setText("Php "+total);
            selectedServices.remove(cbHairCare1.getText());
            
        }
    }//GEN-LAST:event_cbHairCare1ActionPerformed

    private void cbHairCare2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHairCare2ActionPerformed
        if(cbHairCare2.isSelected()) {
            addService(1500);
            lbTotal.setText("Php "+total);
            selectedServices.add(cbHairCare2.getText());
           
        } else {
            removeService(1500);
            lbTotal.setText("Php "+total);
            selectedServices.remove(cbHairCare2.getText());
            
        }
    }//GEN-LAST:event_cbHairCare2ActionPerformed

    private void cbHairCare3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHairCare3ActionPerformed
        if(cbHairCare3.isSelected()) {
            addService(800);
            lbTotal.setText("Php "+total);
            selectedServices.add(cbHairCare3.getText());
        } else {
            removeService(800);
            lbTotal.setText("Php "+total);
            selectedServices.remove(cbHairCare3.getText());
        }
    }//GEN-LAST:event_cbHairCare3ActionPerformed

    private void cbHairCare4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHairCare4ActionPerformed
        if(cbHairCare4.isSelected()) {
            addService(500);
            lbTotal.setText("Php "+total);
            selectedServices.add(cbHairCare4.getText());
        } else {
            removeService(500);
            lbTotal.setText("Php "+total);
            selectedServices.remove(cbHairCare4.getText());
        }
    }//GEN-LAST:event_cbHairCare4ActionPerformed

    private void cbBodyMassage4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBodyMassage4ActionPerformed
        if(cbBodyMassage4.isSelected()) {
            addService(600);
            lbTotal.setText("Php "+total);
            selectedServices.add(cbBodyMassage4.getText());
        } else {
            removeService(600);
            lbTotal.setText("Php "+total);
            selectedServices.remove(cbBodyMassage4.getText());
        }
    }//GEN-LAST:event_cbBodyMassage4ActionPerformed

    private void cbBodyMassage3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBodyMassage3ActionPerformed
        if(cbBodyMassage3.isSelected()) {
            addService(250);
            lbTotal.setText("Php "+total);
            selectedServices.add(cbBodyMassage3.getText());
        } else {
            removeService(250);
            lbTotal.setText("Php "+total);
            selectedServices.remove(cbBodyMassage3.getText());
        }
    }//GEN-LAST:event_cbBodyMassage3ActionPerformed

    private void cbBodyMassage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBodyMassage2ActionPerformed
        if(cbBodyMassage2.isSelected()) {
            addService(250);
            lbTotal.setText("Php "+total);
            selectedServices.add(cbBodyMassage2.getText());
        } else {
            removeService(250);
            lbTotal.setText("Php "+total);
            selectedServices.remove(cbBodyMassage2.getText());
        }
    }//GEN-LAST:event_cbBodyMassage2ActionPerformed

    private void cbBodyMassage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBodyMassage1ActionPerformed
        if(cbBodyMassage1.isSelected()) {
            addService(500);
            lbTotal.setText("Php "+total);
            selectedServices.add(cbBodyMassage1.getText());
        } else {
            removeService(500);
            lbTotal.setText("Php "+total);
            selectedServices.remove(cbBodyMassage1.getText());
        }
    }//GEN-LAST:event_cbBodyMassage1ActionPerformed

    private void cbWaxing1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbWaxing1ActionPerformed
        if(cbWaxing1.isSelected()) {
            addService(600);
            lbTotal.setText("Php "+total);
            selectedServices.add(cbWaxing1.getText());
        } else {
            removeService(600);
            lbTotal.setText("Php "+total);
            selectedServices.remove(cbWaxing1.getText());
        }
    }//GEN-LAST:event_cbWaxing1ActionPerformed

    private void cbWaxing2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbWaxing2ActionPerformed
        if(cbWaxing2.isSelected()) {
            addService(250);
            lbTotal.setText("Php "+total);
            selectedServices.add(cbWaxing2.getText());
        } else {
            removeService(250);
            lbTotal.setText("Php "+total);
            selectedServices.remove(cbWaxing2.getText());
        }
    }//GEN-LAST:event_cbWaxing2ActionPerformed

    private void cbWaxing3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbWaxing3ActionPerformed
        if(cbWaxing3.isSelected()) {
            addService(250);
            lbTotal.setText("Php "+total);
            selectedServices.add(cbWaxing3.getText());
        } else {
            removeService(250);
            lbTotal.setText("Php "+total);
            selectedServices.remove(cbWaxing3.getText());
        }
    }//GEN-LAST:event_cbWaxing3ActionPerformed

    private void cbWaxing4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbWaxing4ActionPerformed
        if(cbWaxing4.isSelected()) {
            addService(400);
            lbTotal.setText("Php "+total);
            selectedServices.add(cbWaxing4.getText());
        } else {
            removeService(400);
            lbTotal.setText("Php "+total);
            selectedServices.remove(cbWaxing4.getText());
        }
    }//GEN-LAST:event_cbWaxing4ActionPerformed

    private void cbNailCare1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNailCare1ActionPerformed
        if(cbNailCare1.isSelected()) {
            addService(250);
            lbTotal.setText("Php "+total);
            selectedServices.add(cbNailCare1.getText());
        } else {
            removeService(250);
            lbTotal.setText("Php "+total);
            selectedServices.remove(cbNailCare1.getText());
        }
    }//GEN-LAST:event_cbNailCare1ActionPerformed

    private void cbNailCare2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNailCare2ActionPerformed
        if(cbNailCare2.isSelected()) {
            addService(125);
            lbTotal.setText("Php "+total);
            selectedServices.add(cbNailCare2.getText());
        } else {
            removeService(125);
            lbTotal.setText("Php "+total);
            selectedServices.remove(cbNailCare2.getText());
        }
    }//GEN-LAST:event_cbNailCare2ActionPerformed

    private void cbNailCare3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNailCare3ActionPerformed
        if(cbNailCare3.isSelected()) {
            addService(125);
            lbTotal.setText("Php "+total);
            selectedServices.add(cbNailCare3.getText());
        } else {
            removeService(125);
            lbTotal.setText("Php "+total);
            selectedServices.remove(cbNailCare3.getText());
        }
    }//GEN-LAST:event_cbNailCare3ActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
      
    
        // dequeue
        queueName.poll();
        
        //refreshing the queue panel
        refreshQueuePanel();
        
       
    }//GEN-LAST:event_btDeleteActionPerformed

    private void jcSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcSexActionPerformed
        
        
    }//GEN-LAST:event_jcSexActionPerformed

    private void btConfirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirm1ActionPerformed
           
          
      try {
           name = tfname.getText();
           sex = jcSex.getSelectedItem().toString();
           contact = tfcontactnumber.getText();

           if (name.isEmpty() || contact.isEmpty()) {
               JOptionPane.showMessageDialog(null, "Your details are incomplete.", "Oops! You forgot something", JOptionPane.ERROR_MESSAGE);
           } else {
               payment = Double.parseDouble(tpAmount.getText());

               if (payment >= total) {
                   receiptPanel.removeAll();
                   receiptPanel.revalidate();
                   receiptPanel.repaint();


                   JLabel textLabe20 = new JLabel(" ");
                   receiptPanel.add(textLabe20);
                   
                   JLabel textLabel7 = new JLabel("Name: " + name);
                   receiptPanel.add(textLabel7);
                   textLabel7.setFont(new Font("Arial", Font.PLAIN, 15));
                   
                   JLabel textLabel8 = new JLabel("Contact Number: " + contact);
                   receiptPanel.add(textLabel8);
                   textLabel8.setFont(new Font("Arial", Font.PLAIN, 15));
                   
                   JLabel textLabel9 = new JLabel("Sex: " + sex);
                   receiptPanel.add(textLabel9);
                   textLabel9.setFont(new Font("Arial", Font.PLAIN, 15));
                   
                   JLabel textLabel6 = new JLabel("------------------------------------------------------");
                   receiptPanel.add(textLabel6);
                   textLabel6.setFont(new Font("Arial", Font.PLAIN, 15));
                   
                   for (String text : selectedServices)
                   {                                  
                       JLabel textLabel1 = new JLabel("  " + text);                                                          
                       textLabel1.setFont(new Font("Arial", Font.PLAIN, 15));
                       receiptPanel.add(textLabel1);
                   }
                   JLabel textLabel2 = new JLabel("------------------------------------------------------");
                   receiptPanel.add(textLabel2);
                   textLabel2.setFont(new Font("Arial", Font.PLAIN, 15));
                   

                   JLabel textLabel3 = new JLabel("Total: Php " + total);
                   receiptPanel.add(textLabel3);
                   textLabel3.setFont(new Font("Arial", Font.PLAIN, 15));
                   

                   JLabel textLabel4 = new JLabel("Received: Php " + payment);
                   receiptPanel.add(textLabel4);
                   textLabel4.setFont(new Font("Arial", Font.PLAIN, 15));
                   

                   change = payment - total;

                   JLabel textLabel5 = new JLabel("Change: Php " + change);
                   receiptPanel.add(textLabel5);
                   textLabel5.setFont(new Font("Arial", Font.PLAIN, 15));
                   

                   receiptWindow.setLocationRelativeTo(null);
                   receiptWindow.setVisible(true);
               } else {
                   JOptionPane.showMessageDialog(null, "Insufficient amount.", "Error", JOptionPane.ERROR_MESSAGE);
               }
           }

       } catch(NumberFormatException e) {
           JOptionPane.showMessageDialog(null, "Invalid input.", "Error", JOptionPane.ERROR_MESSAGE);
       }

      
    }//GEN-LAST:event_btConfirm1ActionPerformed

    // refreshing the queue panel whil also removing the existng components
    public void refreshQueuePanel() {
        
        // removing components to the panel
        plQueue.removeAll();
        // revalidating to reflect the changes
        plQueue.revalidate();
        //repainting to make sure it is updated
        plQueue.repaint();
        plQueue.setLayout(new BoxLayout(plQueue, BoxLayout.Y_AXIS));
        
        // showing the queue panel with updated names
        for(String qn: queueName) {
            
            
        JLabel textLabel5 = new JLabel(qn);
        plQueue.add(textLabel5);
        textLabel5.setFont(new Font("Segoe UI variablle", Font.PLAIN, 20));
        textLabel5.setAlignmentX(Component.CENTER_ALIGNMENT);
        }
    }
    
    private void btConfirm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirm2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConfirm2ActionPerformed

    private void btConfirm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirm3ActionPerformed

        
        // code for the button in the receipt
        receiptPanel.removeAll();
        receiptPanel.revalidate();
        receiptPanel.repaint();
        
        // close the receipt button
        receiptWindow.dispose();
        queueName.add(name);
        refreshQueuePanel();
    }//GEN-LAST:event_btConfirm3ActionPerformed

    private void tfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameActionPerformed

    public void addService(int price) {
        total += price;
    }
    
    public void removeService(int price) {
        total -= price;
    }
    
    public void removeSelectedService(String serviceName) {
        
        
        for(String ss: selectedServices) {
            if(ss.equals(serviceName)) {
                selectedServices.remove(ss);
            }
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Services_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Services_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Services_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Services_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Services_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirm1;
    private javax.swing.JButton btConfirm2;
    private javax.swing.JButton btConfirm3;
    private javax.swing.JButton btDelete;
    private javax.swing.JCheckBox cbBodyMassage1;
    private javax.swing.JCheckBox cbBodyMassage2;
    private javax.swing.JCheckBox cbBodyMassage3;
    private javax.swing.JCheckBox cbBodyMassage4;
    private javax.swing.JCheckBox cbHairCare1;
    private javax.swing.JCheckBox cbHairCare2;
    private javax.swing.JCheckBox cbHairCare3;
    private javax.swing.JCheckBox cbHairCare4;
    private javax.swing.JCheckBox cbNailCare1;
    private javax.swing.JCheckBox cbNailCare2;
    private javax.swing.JCheckBox cbNailCare3;
    private javax.swing.JCheckBox cbWaxing1;
    private javax.swing.JCheckBox cbWaxing2;
    private javax.swing.JCheckBox cbWaxing3;
    private javax.swing.JCheckBox cbWaxing4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcSex;
    private javax.swing.JLabel lbNailCare;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbWaxing;
    private javax.swing.JLabel lbbodymassage;
    private javax.swing.JLabel lbhaircare;
    private javax.swing.JLabel lbhaircare1;
    private javax.swing.JLabel lbhaircare2;
    private javax.swing.JLabel lbquestion1;
    private javax.swing.JLabel lbquestion2;
    private javax.swing.JLabel lbquestion3;
    private javax.swing.JLabel lbquestion4;
    private javax.swing.JLabel lbquestion5;
    private javax.swing.JLabel lbquestion6;
    private javax.swing.JPanel plQueue;
    private javax.swing.JPanel receiptPanel;
    private javax.swing.JFrame receiptWindow;
    private javax.swing.JTextField tfcontactnumber;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextPane tpAmount;
    // End of variables declaration//GEN-END:variables

    private void handleRadioButtonSelection(ActionEvent evt, JCheckBox cbHairCare1, JCheckBox cbHairCare2, JCheckBox cbHairCare3, JCheckBox cbHairCare4) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void handleRadioButtonSelection(ActionEvent evt, JCheckBox cbNailCare1, JCheckBox cbNailCare2, JCheckBox cbNailCare3) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
